pull_request_templates:
  - name: "Standard Pull Request"
    filename: "pull_request.yaml"
    description: "General template for features and enhancements"

  - name: "Bug Fix"
    filename: "bug_fix.yaml"
    description: "Template for bug fixes"

  - name: "Feature/Enhancement"
    filename: "feature_pr.yaml"
    description: "Template for new features or enhancements"

