pull_request_templates: 
  - name: "Standard Pull Request"
    filename: "pull_request.md"
    description: "General template for feature and enhancements"

  - name: "Bug Fix"
    filename: "bug_fix.md"
    description: "Template for bug fixes"
