blank_issue_enabled: false

issue_templates:
  - name: "Bug Report"
    description: "Report a bug in the system."
    title: "[Bug]: "
    labels: ["bug"]
    body: "./bug_report.md"

  - name: "Feature Request"
    description: "Propose a new feature or improvement."
    title: "[Feature]: "
    labels: ["enhancement"]
    body: "./feature_request.md"   

  - name: "Issue Report" 
    description: "Report an issue in the system."
    title: "[Issue]: "
    labels: ["issue"]
    body: "./issue_report.md"
