apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: frontend
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 8080       # Service port
      targetPort: 8080 # Container port
  type: ClusterIP
