apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - ../../base/namespaces.yaml
  - ../../base/configmap.yml
  - ../../base/secrets.yml
  - ../../base/vote-deployment.yml
  - ../../base/vote-service.yml
  - ../../base/result-deployment.yml
  - ../../base/result-service.yml
  - ../../base/worker-deployment.yml
  - ../../base/worker-service.yml
  - ../../base/backend-networkpolicy.yml

images:
  - name: vote
    newName: vote
    newTag: latest
  - name: result
    newName: result
    newTag: latest
  - name: work
    newName: work
    newTag: latest

